using Microsoft.AspNetCore.Mvc;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Demo.PL.Controllers
{
    public class Policies : Controller
    {
        #region Index
        public IActionResult Index()
        {
            return View();
        }

        #endregion

        #region Options
        public class Policy
        {
            public string Icon { get; set; } = "";
            public string Title { get; set; } = "";
            public string Content { get; set; } = "";
        }

        public static class PoliciesPdfGenerator
        {
            public static byte[] Generate(List<Policy> policies)
            {
                var generatedDateTime = DateTime.Now;

                var doc = Document.Create(container =>
                {
                    container.Page(page =>
                    {
                        page.Margin(20);
                        page.Size(PageSizes.A4);

                        page.Header()
                            .Column(column =>
                            {
                                column.Item().Text("Organization Policies & Rules").FontSize(24).Bold();
                                column.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                            });

                        page.Content()
                            .Column(column =>
                            {
                                foreach (var policy in policies)
                                {
                                    column.Item().PaddingVertical(5).Border(1).BorderColor(Colors.Grey.Lighten2)
                                        .Padding(10)
                                        .Column(card =>
                                        {
                                            card.Item().Text($"{policy.Icon} {policy.Title}").FontSize(14).SemiBold().FontColor(Colors.Blue.Medium);
                                            card.Item().Text(policy.Content).FontSize(12);
                                        });
                                }
                            });

                        page.Footer()
                            .AlignCenter()
                            .Column(column =>
                            {
                                column.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                                column.Item().Text($"Generated by SCS on {generatedDateTime:yyyy-MM-dd HH:mm:ss}").FontSize(10);
                                column.Item().AlignCenter().Text(x =>
                                {
                                    x.Span("Page ");
                                    x.CurrentPageNumber();
                                    x.Span(" / ");
                                    x.TotalPages();
                                });
                            });
                    });
                });

                return doc.GeneratePdf();
            }
        }
        #endregion

        #region PDF
        public IActionResult GeneratePdf()
        {
            var policies = new List<Policy>
            {
                new Policy
                {
                    Icon = "🕒",
                    Title = "1. Working Hours",
                    Content = "Employees are expected to work from 9:00 AM to 5:00 PM, Sunday through Thursday. Flexible working hours may be approved by management in special cases."
                },
                new Policy
                {
                    Icon = "📅",
                    Title = "2. Leave Policy",
                    Content = "Annual leave must be approved at least 1 week in advance. Sick leave requires a valid medical certificate if longer than 2 days. Emergency leave should be reported as soon as possible to the manager."
                },
                new Policy
                {
                    Icon = "🔒",
                    Title = "3. Confidentiality",
                    Content = "All employees must protect company data and refrain from sharing sensitive information outside the company. Violation of this policy may result in disciplinary action, including termination."
                },
                new Policy
                {
                    Icon = "👥",
                    Title = "4. Code of Conduct",
                    Content = "Maintain professionalism and integrity at all times. Respect colleagues, clients, and organizational culture. Avoid conflicts of interest and report any unethical behavior."
                },
                new Policy
                {
                    Icon = "💻",
                    Title = "5. Use of Company Assets",
                    Content = "Company equipment (computers, software, vehicles, etc.) must be used responsibly and only for official purposes. Unauthorized use is strictly prohibited."
                },
                new Policy
                {
                    Icon = "🏥",
                    Title = "6. Health & Safety",
                    Content = "Employees must comply with health and safety regulations. Report unsafe conditions immediately. Emergency procedures should be followed as per training."
                }
            };

            var pdfBytes = PoliciesPdfGenerator.Generate(policies);
            return File(pdfBytes, "application/pdf", "Policies.pdf");
        }
        #endregion
    }
}
