using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Demo.PL.ViewModels;

namespace Demo.PL.PdfGenerators
{
    public static class DashboardPdfGenerator
    {
        public static byte[] Generate(HomeViewModel model)
        {
            var generatedDateTime = DateTime.Now;

            var doc = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);
                    page.Size(PageSizes.A4);

                    page.Header()
                        .Column(column =>
                        {
                            column.Item().Text("SCS Dashboard Report").FontSize(24).Bold();
                            column.Item().Text($"Generated by SCS on: {generatedDateTime:yyyy-MM-dd HH:mm:ss}").FontSize(10);
                            column.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                        });

                    page.Content()
                        .Column(column =>
                        {
                            // Summary Counts
                            column.Item()
                                .PaddingBottom(5)
                                .Row(row =>
                                {
                                    row.RelativeItem().Text($"Departments: {model.DepartmentsCount}");
                                    row.RelativeItem().Text($"Employees: {model.EmployeesCount}");
                                    row.RelativeItem().Text($"Users: {model.UsersCount}");
                                });

                            column.Item()
                                .PaddingBottom(5)
                                .Row(row =>
                                {
                                    row.RelativeItem().Text($"Total Sales Invoices: {model.TotalSales:C}");
                                    row.RelativeItem().Text($"Total Purchases Invoices: {model.TotalPurchases:C}");
                                    row.RelativeItem().Text($"Invoices Net Profit: {model.NetProfit:C}");
                                });

                            column.Item()
                                .PaddingTop(5)
                                .Text($"Employees Total Salaries: {model.EmployeesTotalSalaries:C}");

                            // Top Clients
                            column.Item().PaddingVertical(5).Text("Top 5 Clients").FontSize(14).Bold().FontColor(Colors.Green.Medium);
                            if (model.TopClients.Any())
                            {
                                column.Item().Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.RelativeColumn(3);
                                        columns.RelativeColumn(2);
                                    });

                                    table.Header(header =>
                                    {
                                        header.Cell().Text("Client Name").SemiBold();
                                        header.Cell().Text("Total Purchased").SemiBold();
                                    });

                                    foreach (var c in model.TopClients)
                                    {
                                        table.Cell().Text(c.ClientName);
                                        table.Cell().Text(c.TotalPurchased.ToString("C")).AlignRight();
                                    }
                                });
                            }
                            else
                            {
                                column.Item().Text("No data available.");
                            }

                            // Top Sellers
                            column.Item().PaddingVertical(5).Text("Top 5 Sellers").FontSize(14).Bold().FontColor(Colors.Orange.Medium);
                            if (model.TopSellers.Any())
                            {
                                column.Item().Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.RelativeColumn(3);
                                        columns.RelativeColumn(2);
                                    });

                                    table.Header(header =>
                                    {
                                        header.Cell().Text("Seller Name").SemiBold();
                                        header.Cell().Text("Total Supplied").SemiBold();
                                    });

                                    foreach (var s in model.TopSellers)
                                    {
                                        table.Cell().Text(s.SellerName);
                                        table.Cell().Text(s.TotalSupplied.ToString("C")).AlignRight();
                                    }
                                });
                            }
                            else
                            {
                                column.Item().Text("No data available.");
                            }

                            // Top Categories
                            column.Item().PaddingVertical(5).Text("Top 5 Categories").FontSize(14).Bold().FontColor(Colors.Purple.Medium);
                            if (model.TopCategories.Any())
                            {
                                column.Item().Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.RelativeColumn(3);
                                        columns.RelativeColumn(2);
                                    });

                                    table.Header(header =>
                                    {
                                        header.Cell().Text("Category Name").SemiBold();
                                        header.Cell().Text("Total Amount").SemiBold();
                                    });

                                    foreach (var c in model.TopCategories)
                                    {
                                        table.Cell().Text(c.CategoryName);
                                        table.Cell().Text(c.TotalAmount.ToString("C")).AlignRight();
                                    }
                                });
                            }
                            else
                            {
                                column.Item().Text("No data available.");
                            }
                        });

                    // ---------- Footer ----------
                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Page ");
                            x.CurrentPageNumber();
                            x.Span(" / ");
                            x.TotalPages();
                        });
                });
            });

            return doc.GeneratePdf();
        }
    }
}
