using Demo.PL.ViewModels;
using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using QuestPDF.Helpers;

public class EmployeePdfService
{
    public byte[] GenerateEmployeePdf(EmployeeViewModel employee)
    {
        var pdf = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(12));

                // Header
                page.Header().Column(col =>
                {
                    col.Item().Text("Generated By SCS")
                        .SemiBold().FontSize(18).FontColor(Colors.Blue.Medium)
                        .AlignCenter();

                    col.Item().Text("Employee Details")
                        .Bold().FontSize(16)
                        .AlignCenter();

                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                });

                // Content
                page.Content().Column(content =>
                {
                    content.Spacing(15);

                    // Employee Image
                    if (!string.IsNullOrEmpty(employee.ExistingImageName))
                    {
                        content.Item().Text("Employee Image:").SemiBold();
                        content.Item().Height(150).Width(150).Image(
                            $"wwwroot/Files/Images/{employee.ExistingImageName}",
                            ImageScaling.FitArea);
                    }
                    else
                    {
                        content.Item().Text("Employee Image: None").Italic();
                    }

                    // Details in Category / Data table
                    content.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.ConstantColumn(150); 
                            cols.RelativeColumn();     
                        });

                        void AddRow(string category, string data)
                        {
                            table.Cell().Element(CellStyle).Text(category).SemiBold();
                            table.Cell().Element(CellStyle).Text(data);
                        }

                        AddRow("Name:", employee.Name);
                        AddRow("Email:", employee.Email);
                        AddRow("Phone:", employee.PhoneNumber);
                        AddRow("Age:", employee.Age.ToString());
                        AddRow("Address:", employee.Address);
                        AddRow("Role:", employee.Role);
                        AddRow("Hiring Date:", employee.HiringDate.ToString("yyyy-MM-dd"));
                        AddRow("Salary:", employee.Salary.ToString("F2"));
                        AddRow("Active:", employee.IsActive ? "Yes" : "No");
                        AddRow("DepartmentID:", employee.DepartmentID.ToString());
                        AddRow("Gender:", employee.gender.ToString());
                    });
                });

                // Footer
                page.Footer().AlignCenter().Text(
                    $"Generated on: {DateTime.Now:yyyy-MM-dd HH:mm}"
                );
            });
        });

        return pdf.GeneratePdf();
    }

    private IContainer CellStyle(IContainer container)
    {
        return container
            .PaddingVertical(5)
            .BorderBottom(1)
            .BorderColor(Colors.Grey.Lighten2);
    }
}
