using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using Demo.DAL.Models.Invoice.PurchasesInvoice;
using QuestPDF.Helpers;

public static class PurchaseInvoicePdfGenerator
{
    public static byte[] Generate(PurchaseInvoice invoice)
    {
        var generatedDateTime = DateTime.Now;

        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(20);
                page.Size(PageSizes.A4);

                // ---------- Header ----------
                page.Header()
                    .Column(column =>
                    {
                        column.Item().Text("Purchase Invoice").FontSize(24).Bold();
                        column.Item().Text($"Invoice Code: {invoice.InvoiceCode}").FontSize(12);
                        column.Item().Text($"Seller: {invoice.Seller?.Name ?? ""}").FontSize(12);
                        column.Item().Text($"Invoice Date: {invoice.InvoiceDate:yyyy-MM-dd}").FontSize(12);
                        column.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                    });

                // ---------- Items Table ----------
                page.Content()
                    .Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3); // Item
                            columns.RelativeColumn(2); // Quantity
                            columns.RelativeColumn(2); // Unit Price
                            columns.RelativeColumn(2); // Percentage
                            columns.RelativeColumn(2); // Type
                            columns.RelativeColumn(2); // Final Total
                        });

                        // Table Header
                        table.Header(header =>
                        {
                            header.Cell().Text("Item").SemiBold();
                            header.Cell().Text("Quantity").SemiBold().AlignCenter();
                            header.Cell().Text("Unit Price").SemiBold().AlignCenter();
                            header.Cell().Text("Percentage (%)").SemiBold().AlignCenter();
                            header.Cell().Text("Type").SemiBold().AlignCenter();
                            header.Cell().Text("Total").SemiBold().AlignCenter();
                        });

                        decimal grandTotal = 0;

                        // Table Rows
                        foreach (var item in invoice.Items)
                        {
                            decimal quantity = item.Quantity;
                            decimal unitPrice = item.UnitPrice;
                            decimal percentage = item.Percentage ?? 0;
                            bool isAdded = item.IsPercentageAdded;

                            decimal baseTotal = quantity * unitPrice;
                            decimal percentageValue = baseTotal * (percentage / 100);
                            decimal finalTotal = isAdded ? baseTotal + percentageValue : baseTotal - percentageValue;

                            grandTotal += finalTotal;

                            table.Cell().Text(item.Category?.Name ?? "");
                            table.Cell().Text(quantity.ToString("0")).AlignCenter();
                            table.Cell().Text(unitPrice.ToString("0.00")).AlignCenter();
                            table.Cell().Text($"{percentage:0.##} %").AlignCenter();
                            table.Cell().Text(isAdded ? "Added (+)" : "Subtracted (-)").AlignCenter();
                            table.Cell().Text(finalTotal.ToString("0.00")).AlignCenter();
                        }

                        // Table Footer - Grand Total
                        table.Footer(footer =>
                        {
                            footer.Cell().ColumnSpan(5).AlignRight().Text("Total Cost").Bold();
                            footer.Cell().Text(grandTotal.ToString("0.00")).Bold().AlignCenter();
                        });
                    });

                // ---------- Footer ----------
                page.Footer()
                    .AlignCenter()
                    .Column(column =>
                    {
                        column.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                        column.Item().Text($"Generated by SCS on {generatedDateTime:yyyy-MM-dd HH:mm:ss}").FontSize(10);
                    });
            });
        });

        return doc.GeneratePdf();
    }
}
